# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependacies
        run: sudo apt-get update && sudo apt-get install python3 && sudo apt-get install pip && pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Run the example python file
        run: python3 example.py

      - name: Run the main python file
        run: python3 main.py
